apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nodejs-prometheus.fullname" . }}
  labels:
    app: {{ include "nodejs-prometheus.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "nodejs-prometheus.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "nodejs-prometheus.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
            requests:
              cpu: "100m"
              memory: "256Mi"
