apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nodejs-prometheus-servicemonitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      release: nodejs-prometheus
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
  namespaceSelector:
    matchNames:
      - nodejs-prometheus
